name: Build SO Image

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Packer
        uses: hashicorp/setup-packer@v3.1.0
        with:
          version: latest

      - name: Install QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system-x86 qemu-utils

      - name: Download Ubuntu ISO (24.04.1 live-server)
        run: |
          mkdir -p iso
          curl -L -o iso/ubuntu-24.04-live-server.iso \
            https://old-releases.ubuntu.com/releases/24.04/ubuntu-24.04.1-live-server-amd64.iso

          # sanity check: ISO tem que ter pelo menos 1GB
          SIZE=$(stat -c%s iso/ubuntu-24.04-live-server.iso)
          if [ "$SIZE" -lt 1000000000 ]; then
            echo "ISO muito pequena ($SIZE bytes), download falhou."
            exit 1
          fi

      - name: Packer init
        run: packer init so-autoinstall.pkr.hcl

      - name: Packer validate
        run: packer validate so-autoinstall.pkr.hcl

      - name: Packer build
        run: packer build -color=false so-autoinstall.pkr.hcl

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: so-ubuntu-image
          path: output/
